eureka:
  client:
#    register-with-eureka: true
#    fetch-registry: true
    service-url.defaultZone: "http://liyq:123@euk1.com:7001/eureka/"
  instance:
    metadata-map.dalao: consumer-chinaliyq
#    appname: consumer-1
server:
  port: 91
spring:
  application:
    name: consumer
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true