eureka:
  client:
    service-url.defaultZone: "http://liyq:123@euk1.com:7001/eureka/"
server:
  port: 90

spring:
  application:
    name: consumer

ribbon.ConnectTimeout: 1000
ribbon.ReadTimeout: 2000

#同一台实例最大重试次数,不包括首次调用
ribbon.MaxAutoRetries: 3
#重试负载均衡其他的实例最大重试次数,不包括首次调用
ribbon.MaxAutoRetriesNextServer: 3
#是否所有操作都重试
ribbon.OkToRetryOnAllOperations: false
